version: '3.9'

services:
  api:
    container_name: shop-crud-api
    build: .
    volumes:
      - ./:/app
    ports:
      - "80:80"
    links:
      - db:mysql
    depends_on:
      - db

  db:
    container_name: shop-crud-api-db
    platform: linux/x86_64
    image: mysql
    restart: always
    volumes:
      - database-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

volumes:
  database-volume:
